import fs from 'node:fs/promises'
import path from 'node:path'
import type { ManifestEntry } from '../schemas/plan.js'
import { resolveLoopPaths } from '../store/paths.js'
import { listPlanIds } from '../store/plan-store.js'
import type { Clock } from '../store/state-store.js'
import { renderManifest } from './manifest.js'

const HEADER = '<!-- generated by loop_index_render — do not edit -->'

/**
 * Derived, never stored: a status kept alongside the stories it summarises is
 * a status that can disagree with them.
 */
export function planStatus(stories: ManifestEntry[]): 'planned' | 'in-progress' | 'blocked' | 'done' {
  if (stories.length === 0) return 'planned'
  if (stories.every((story) => story.status === 'done')) return 'done'

  const started = stories.some((story) => story.status === 'done' || story.status === 'doing')
  const stalled = stories.every((story) => story.status === 'done' || story.status === 'blocked')
  if (stalled && stories.some((story) => story.status === 'blocked')) return 'blocked'
  return started ? 'in-progress' : 'planned'
}

export async function renderIndex(projectDir: string, now: Clock = () => new Date()): Promise<string> {
  const planIds = await listPlanIds(projectDir)
  const paths = resolveLoopPaths(projectDir)

  let markdown: string
  if (planIds.length === 0) {
    markdown = `${HEADER}\n\nNo plans yet.\n`
  } else {
    const rows: string[] = []
    for (const planId of planIds) {
      // Rendering the manifest first means the index can never be newer than
      // the manifests it summarises.
      const manifest = await renderManifest(projectDir, planId, now)
      const done = manifest.stories.filter((story) => story.status === 'done').length
      rows.push(
        `| ${manifest.plan} | ${manifest.title} | ${manifest.stories.length} | ${done} | ${planStatus(manifest.stories)} |`,
      )
    }
    markdown = [
      HEADER,
      '',
      '| Plan | Title | Stories | Done | Status |',
      '|------|-------|---------|------|--------|',
      ...rows,
      '',
    ].join('\n')
  }

  await fs.mkdir(path.dirname(paths.index), { recursive: true })
  await fs.writeFile(paths.index, markdown, 'utf8')
  return markdown
}
